name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: |
          go mod tidy
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build APK (arm64)
        run: |
          # Memaksa penggunaan icon.png dari folder utama
          $HOME/go/bin/fyne-cross android \
            -app-id com.kalender.selamatan \
            -name "Cek Selamatan" \
            -arch arm64 \
            -icon icon.png \
            -silent

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Selamatan-Premium
          # Jalur diperluas agar mencakup semua sub-folder di dalam dist
          path: fyne-cross/dist/**/*.apk


name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: |
          go mod tidy
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build APK (arm64)
        run: |
          # Memaksa penggunaan icon.png dari folder utama
          $HOME/go/bin/fyne-cross android \
            -app-id com.exe.rich \
            -name "my executor" \
            -icon icon.png \
            -arch arm64 \
            -metadata "android:requestLegacyExternalStorage=true" \
            -permission "android.permission.MANAGE_EXTERNAL_STORAGE" \
            -permission "android.permission.READ_EXTERNAL_STORAGE" \
            -permission "android.permission.WRITE_EXTERNAL_STORAGE" \
            -permission "android.permission.INTERNET" \
            -silent

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-executor
          # Jalur diperluas agar mencakup semua sub-folder di dalam dist
          path: fyne-cross/dist/**/*.apk
