name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: |
          go mod tidy
          # PERBAIKAN: Menambahkan '/v2' agar sesuai dengan versi terbaru
          go install github.com/fyne-io/fyne-cross/v2/cmd/fyne-cross@latest

      - name: Build APK (arm64)
        run: |
          # Perintah build dengan permission lengkap
          $HOME/go/bin/fyne-cross android \
            -app-id com.tangsan.executor \
            -name "Simple Exec" \
            -icon fd.png \
            -arch arm64 \
            -metadata "android:requestLegacyExternalStorage=true" \
            -permission "android.permission.MANAGE_EXTERNAL_STORAGE" \
            -permission "android.permission.READ_EXTERNAL_STORAGE" \
            -permission "android.permission.WRITE_EXTERNAL_STORAGE" \
            -permission "android.permission.INTERNET" \
            -silent

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-executor
          path: fyne-cross/dist/**/*.apk

